### ISSUE TITLE
Cannot get dockerhub image to work

### ISSUE THREAD

**Issue by MLnick** [IBM/MAX-Facial-Age-Estimator-Web-App#12]
Consistently getting the following error trying to run the public dockerhub image:

```
docker run --net='container:max-facial-age-estimator' -it codait/max-facial-age-estimator-web-app
Unable to find image 'codait/max-facial-age-estimator-web-app:latest' locally
latest: Pulling from codait/max-facial-age-estimator-web-app
05d1a5232b46: Already exists
5cee356eda6b: Already exists
89d3385f0fd3: Already exists
80ae6b477848: Already exists
28bdf9e584cc: Already exists
a0cd6b0afff0: Already exists
cd4c682e75b6: Already exists
ac1b7290f23f: Already exists
5c60877508b0: Already exists
d0c492582cf0: Pull complete
456e4a6c2d71: Pull complete
aee9723bc882: Pull complete
9b46b7267cdd: Pull complete
Digest: sha256:4030649abcc33059aadab9eb8288cfa438fe5fe589088bba9bfd0aa7c637b31e
Status: Downloaded newer image for codait/max-facial-age-estimator-web-app:latest
Traceback (most recent call last):
  File "app.py", line 31, in <module>
    import queue
ImportError: No module named queue
```

cc @ajbozarth

**Comment by mighani** [comment]
the Docker Image is for python 2.7 but code uses "queue" which is available in python 3.x I remember that there was also a queue class in python 2.7 but maybe in different package/module.

**Comment by ajbozarth** [comment]
I'll take a look at why my try/except import block for queue isn't working for the docker image as expected

**Comment by ajbozarth** [comment]
#13 should have fixed this, so give docker hub about 10-30min to propagate the change then check that it works for you @MLnick @mighani

**Comment by MLnick** [comment]
Working now, thanks!

**Comment by QQ601407388** [comment]
python - ImportError: No module named concurrent.futures 
python 2.7 + centos7
after 
pip install futures 
works
