### ISSUE TITLE
App should skip old frames when frames are piling up

### ISSUE THREAD

**Issue by MHBauer** [IBM/MAX-Facial-Age-Estimator-Web-App#14]
When frames are being queued in the app, they should become expired when they become older than a few seconds. If not, they pile up and take more and more memory and become further and further delayed from reappearing in the application.

**Comment by I-Hong** [comment]
Thank you for the useful comment. Do you have any changes for it? I'll be great if you are willing to contribute.

**Comment by djalova** [comment]
This issue is fixed by #22

**Comment by I-Hong** [comment]
By setting queue size is one, there is no such issue.
