### ISSUE TITLE
face bounding box not placed in correct locations

### ISSUE THREAD

**Issue by vabarbosa** [IBM/MAX-Facial-Age-Estimator-Web-App#30]
i used the facial age estimator mini app (i.e., long running demo instance):

http://max-facial-age-estimator-mini-web-app.max.us-south.containers.appdomain.cloud/

and uploaded this image:

https://github.com/IBM/MAX-Human-Pose-Estimator/blob/master/assets/Pilots.jpg

the output i got was this:

![image](https://user-images.githubusercontent.com/13156555/55877878-28759900-5b69-11e9-9748-d066acd68dea.png)

the bounding box for the faces are misplaced.

**Comment by I-Hong** [comment]
Hi @SSaishruthi. Did you create the `mini` version of web-app? If yes, can you please help quickly correct it based on our original version, https://github.com/IBM/MAX-Facial-Age-Estimator and https://github.com/IBM/MAX-Facial-Age-Estimator-Web-App?

**Comment by ajbozarth** [comment]
@vabarbosa if you could open an issue on the mini app repo https://github.com/CODAIT/MAX-Facial-Age-Estimator-Mini-Web-App we can have further discussion there. As for the bug, I'll look into it

**Comment by vabarbosa** [comment]
@ajbozarth done: https://github.com/CODAIT/MAX-Facial-Age-Estimator-Mini-Web-App/issues/8
my bad i wasn't aware there was a separate repo for the mini app instance.
