### ISSUE TITLE
README docker tag issue

### ISSUE THREAD

**Issue by MLnick** [IBM/MAX-Facial-Age-Estimator-Web-App#37]
In section https://github.com/IBM/MAX-Facial-Age-Estimator-Web-App#4-instructions-for-docker-optional, there is a reference to `docker build -t max-age-estimator-web-app .` and `docker run -it --net='container:max-facial-age-estimator' max-age-estimator-web-app`.

the `max-age-estimator-web-app` should be changed to `max-facial-age-estimator-web-app` in these two commands, to be consistent with the MAX standard docker tag naming convention.

**Comment by I-Hong** [comment]
Thanks for pointing out this,  @MLnick.
