### ISSUE TITLE
error in python app.py

### ISSUE THREAD

**Issue by efmopa** [IBM/MAX-Facial-Age-Estimator-Web-App#39]
Traceback (most recent call last):
File "app.py", line 25, in 
from concurrent.futures import ThreadPoolExecutor
ImportError: No module named concurrent.futures

**Comment by I-Hong** [comment]
concurrent.futures in python3, python2 need pip install futures

**Comment by efmopa** [comment]
I installed its dependencies:

pip install -r requirements.txt

**Comment by xuhdev** [comment]
@I-Hong future is not listed in requirements.txt . Could you add it?

**Comment by xuhdev** [comment]
Could you try

    python 3 app.py

**Comment by efmopa** [comment]
Thanks for your reply. I have already solved. I should have created the myenv environment. It already works for me.
